### ISSUE TITLE
Inactive workflow and archieved workflow are using same tab

### ISSUE THREAD

**Issue by cuong-thach** [PipedreamHQ/roadmap#249] opened 2020-01-11 02:39 UTC
**Describe the bug**
Archived workflow has should be on a separate tab with inactive workflows.
https://share.getcloudapp.com/wbukXGbN

**To Reproduce**
https://share.getcloudapp.com/wbukXGbN

**Expected behavior**
All archived workflow only display at Archived Tab.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dylburger** [comment] 2020-01-11 04:08
@cuongtalentccc this is actually by design. When you archive a workflow, we deactivate it, as well. So all archived workflows are also inactive.

Is there a way you think we can improve the categorization, or the labeling / filtering, to make that more clear?

**Comment by dylburger** [comment] 2020-03-05 00:47
We're still happy to consider other options for presenting this UX, but since this isn't a bug, I'm closing the current issue. Feel free to open another issue or chat us on Slack with other ideas.

**Closed by dylburger** 2020-03-05 00:47 UTC
Labels: bug
